# Generated by Django 4.2.5 on 2023-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
