# Generated by Django 4.2.7 on 2023-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assets',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(null=True),
        ),
    ]
