# Generated by Django 4.2.5 on 2023-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_acno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
