# Generated by Django 4.2.5 on 2023-10-25 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_bank_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('user',)},
        ),
    ]
